"""Structured Lab deployment executor.

Runs the deployment plan generated by ``planner.py`` over an existing live SSH
session. It records per-step state in TaskRun.metadata_json so the UI can render
a Mission Timeline without adding deployment-step tables yet.
"""

from __future__ import annotations

import logging
import re
import shlex
import time
from datetime import datetime, timezone
from typing import Callable
from uuid import UUID

from fastapi.encoders import jsonable_encoder

from app.db.session import SessionLocal
from app.models.entities import FailureStage, ModelRunAttempt, RunStatus, TaskRun, TaskStatus
from app.schemas.deployment_plan import DeploymentPlanStep
from app.services import session_store
from app.services.settings_service import get_setting
from app.workers.utils import _finish_task_run, _log_path, _make_logger, _utcnow

logger = logging.getLogger(__name__)

_SECRET_PATTERNS = (
    re.compile(r"hf_[A-Za-z0-9_=-]{12,}"),
    re.compile(r"sk-[A-Za-z0-9_-]{12,}"),
    re.compile(r"sk-ant-[A-Za-z0-9_-]{12,}"),
    re.compile(r"ghp_[A-Za-z0-9_]{12,}"),
)


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _tail(text: str, limit: int = 4000) -> str:
    if len(text) <= limit:
        return text
    return text[-limit:]


def _mask(text: str, known_secrets: list[str] | None = None) -> str:
    masked = text
    for secret in known_secrets or []:
        if secret:
            masked = masked.replace(secret, "[redacted]")
    for pattern in _SECRET_PATTERNS:
        masked = pattern.sub("[redacted]", masked)
    return masked


def _steps_from_metadata(task_run: TaskRun) -> list[DeploymentPlanStep]:
    raw_steps = (task_run.metadata_json or {}).get("steps") or []
    return [DeploymentPlanStep.model_validate(step) for step in raw_steps]


def _write_steps(task_run: TaskRun, db, steps: list[DeploymentPlanStep]) -> None:
    metadata = dict(task_run.metadata_json or {})
    metadata["steps"] = [jsonable_encoder(step) for step in steps]
    task_run.metadata_json = metadata
    db.commit()


def _update_step(
    *,
    task_run: TaskRun,
    db,
    step_id: str,
    **patch,
) -> list[DeploymentPlanStep]:
    steps = _steps_from_metadata(task_run)
    for idx, step in enumerate(steps):
        if step.id == step_id:
            values = step.model_dump()
            values.update(patch)
            steps[idx] = DeploymentPlanStep.model_validate(values)
            break
    _write_steps(task_run, db, steps)
    db.refresh(task_run)
    return steps


def _cancel_requested(task_run: TaskRun, db) -> bool:
    db.refresh(task_run)
    return bool((task_run.metadata_json or {}).get("cancel_requested"))


def _failure_stage(step: DeploymentPlanStep) -> FailureStage:
    if step.id == "pull_image":
        return FailureStage.IMAGE_PULL
    if step.id.startswith("health") or step.stage == "verify":
        return FailureStage.HEALTH_CHECK
    if step.stage == "preflight":
        return FailureStage.PLAN
    if step.stage == "launch":
        return FailureStage.OTHER
    return FailureStage.OTHER


def _extract_container_id(stdout: str) -> str | None:
    for line in stdout.splitlines():
        candidate = line.strip()
        if len(candidate) >= 12 and all(ch in "0123456789abcdef" for ch in candidate.lower()):
            return candidate[:64]
    return None


def _read_vram_used(client) -> float | None:
    try:
        _, stdout, _ = client.exec_command(
            "nvidia-smi --query-gpu=memory.used --format=csv,noheader,nounits",
            timeout=10,
        )
        out = stdout.read().decode(errors="replace")
        rc = stdout.channel.recv_exit_status()
    except Exception:
        return None
    if rc != 0:
        return None
    total_mb = 0
    for line in out.splitlines():
        try:
            total_mb += int(line.strip())
        except ValueError:
            pass
    return round(total_mb / 1024, 2) if total_mb else None


def _exec(client, command: str, timeout: int, hf_token: str | None) -> tuple[str, str, int]:
    expanded = command.replace("$INFERIX_HF_TOKEN", shlex.quote(hf_token or ""))
    wrapped = f"bash -lc {shlex.quote(expanded)}"
    stdin, stdout, stderr = client.exec_command(wrapped, timeout=timeout)
    stdin.close()
    out = stdout.read().decode(errors="replace")
    err = stderr.read().decode(errors="replace")
    rc = stdout.channel.recv_exit_status()
    return out, err, rc


def _poll_health(
    *,
    client,
    command: str,
    timeout_seconds: int,
    hf_token: str | None,
    log: Callable[[str], None],
    mask_secrets: list[str],
) -> tuple[str, str, int]:
    deadline = time.monotonic() + max(1, timeout_seconds)
    attempts = 0
    last_out = ""
    last_err = ""
    while time.monotonic() < deadline:
        attempts += 1
        out, err, rc = _exec(client, command, timeout=12, hf_token=hf_token)
        last_out, last_err = out, err
        if rc == 0:
            log(f"  health attempt {attempts}: ok\n")
            return out, err, 0
        if attempts == 1 or attempts % 5 == 0:
            details = _mask((err or out or "not ready").strip(), mask_secrets)
            log(f"  health attempt {attempts}: waiting ({details[:200]})\n")
        time.sleep(3)
    return last_out, last_err or f"Health check did not pass within {timeout_seconds}s", 1


def run_deployment_task(
    *,
    task_run_id: str,
    model_run_id: str,
    session_id: str,
    auto_setup_mode: str,
    health_timeout_seconds: int,
    command_timeout_seconds: int,
) -> None:
    """Background entrypoint used by the Lab deployment endpoints."""
    db = SessionLocal()
    log_file: str | None = None
    try:
        task_run = db.query(TaskRun).filter(TaskRun.id == UUID(task_run_id)).first()
        run = db.query(ModelRunAttempt).filter(ModelRunAttempt.id == UUID(model_run_id)).first()
        if not task_run or not run:
            return

        log_file = _log_path(task_run_id)
        task_run.logs_path = log_file
        task_run.status = TaskStatus.RUNNING
        task_run.started_at = _utcnow()
        run.status = RunStatus.RUNNING
        db.commit()

        handle = session_store.get(session_id)
        if handle is None:
            raise RuntimeError("No active SSH handle for this session")

        hf_token = get_setting("hf_token", db)
        mask_secrets = [hf_token] if hf_token else []
        steps = _steps_from_metadata(task_run)

        with open(log_file, "w", encoding="utf-8") as log_f:
            log = _make_logger(log_f)
            log("[inferix] starting deployment workflow\n\n")

            for step in steps:
                if _cancel_requested(task_run, db):
                    _update_step(
                        task_run=task_run,
                        db=db,
                        step_id=step.id,
                        status="CANCELLED",
                        finished_at=_now(),
                        error="Cancelled by operator",
                    )
                    task_run.status = TaskStatus.FAILED
                    task_run.error_summary = "Deployment cancelled"
                    run.status = RunStatus.ABANDONED
                    run.succeeded = False
                    run.failure_message = "Deployment cancelled"
                    db.commit()
                    return

                if not step.command:
                    _update_step(task_run=task_run, db=db, step_id=step.id, status="SKIPPED", finished_at=_now())
                    continue

                if (
                    auto_setup_mode == "recommend_only"
                    and step.auto_eligible
                    and step.recommended
                    and step.stage in {"setup", "runtime", "model"}
                ):
                    log(f"$ {step.command}\n")
                    log("  [recommended only] enable auto low-risk setup to run this step automatically\n\n")
                    _update_step(
                        task_run=task_run,
                        db=db,
                        step_id=step.id,
                        status="RECOMMENDED",
                        finished_at=_now(),
                        notes=(step.notes or "Recommended setup step; not auto-run in current settings."),
                    )
                    continue

                log(f"$ {_mask(step.command, mask_secrets)}\n")
                _update_step(task_run=task_run, db=db, step_id=step.id, status="RUNNING", started_at=_now())

                try:
                    if step.id == "health_models":
                        out, err, rc = _poll_health(
                            client=handle.client,
                            command=step.command,
                            timeout_seconds=health_timeout_seconds,
                            hf_token=hf_token,
                            log=log,
                            mask_secrets=mask_secrets,
                        )
                    else:
                        out, err, rc = _exec(
                            handle.client,
                            step.command,
                            timeout=command_timeout_seconds,
                            hf_token=hf_token,
                        )
                except Exception as exc:
                    out, err, rc = "", str(exc), 1

                masked_out = _mask(out, mask_secrets)
                masked_err = _mask(err, mask_secrets)
                if masked_out:
                    log(_tail(masked_out) + ("\n" if not masked_out.endswith("\n") else ""))
                if masked_err:
                    log("--- stderr ---\n" + _tail(masked_err) + ("\n" if not masked_err.endswith("\n") else ""))
                log(f"--- exit code: {rc} ---\n\n")

                if step.id == "launch_vllm":
                    run.launch_command = _mask(step.command, mask_secrets)
                    run.container_id = _extract_container_id(out) or run.container_id
                    db.commit()

                if step.id == "health_models":
                    run.health_check_url = step.command.split(" ", 2)[-1] if "http" in step.command else None
                    run.health_check_ok = rc == 0
                    run.vram_used_gb = _read_vram_used(handle.client)
                    db.commit()

                _update_step(
                    task_run=task_run,
                    db=db,
                    step_id=step.id,
                    status="SUCCESS" if rc == 0 else "FAILED",
                    finished_at=_now(),
                    stdout_tail=_tail(masked_out),
                    stderr_tail=_tail(masked_err),
                    error=None if rc == 0 else (masked_err or masked_out or f"Command exited with {rc}")[:1000],
                )

                if rc != 0 and step.required:
                    run.status = RunStatus.FAILED
                    run.succeeded = False
                    run.failure_stage = _failure_stage(step)
                    run.failure_message = (masked_err or masked_out or f"{step.title} failed")[:4000]
                    task_run.status = TaskStatus.FAILED
                    task_run.error_summary = run.failure_message
                    db.commit()
                    return

            run.status = RunStatus.SUCCESS
            run.succeeded = True
            run.health_check_ok = True if run.health_check_ok is None else run.health_check_ok
            run.vram_used_gb = run.vram_used_gb if run.vram_used_gb is not None else _read_vram_used(handle.client)
            task_run.status = TaskStatus.SUCCESS
            log("[inferix] deployment workflow complete\n")

    except Exception as exc:
        logger.exception("Lab deployment task failed")
        task_run = db.query(TaskRun).filter(TaskRun.id == UUID(task_run_id)).first()
        run = db.query(ModelRunAttempt).filter(ModelRunAttempt.id == UUID(model_run_id)).first()
        if task_run:
            task_run.status = TaskStatus.FAILED
            task_run.error_summary = str(exc)
        if run:
            run.status = RunStatus.FAILED
            run.succeeded = False
            run.failure_stage = FailureStage.OTHER
            run.failure_message = str(exc)[:4000]
        db.commit()
        if log_file:
            try:
                with open(log_file, "a", encoding="utf-8") as log_f:
                    log_f.write(f"\nERROR: {exc}\n")
            except Exception:
                pass
    finally:
        task_run = db.query(TaskRun).filter(TaskRun.id == UUID(task_run_id)).first()
        run = db.query(ModelRunAttempt).filter(ModelRunAttempt.id == UUID(model_run_id)).first()
        if run:
            now = _now()
            run.completed_at = now
            if run.started_at:
                run.duration_seconds = max(0, int((now - run.started_at).total_seconds()))
        if task_run:
            _finish_task_run(task_run, db)
        db.close()


def run_pipeline_step_task(
    *,
    task_run_id: str,
    session_id: str,
    commands: list[str],
    step_name: str,
) -> None:
    """Generic pipeline step: run SSH commands sequentially, stream output to log file."""
    db = SessionLocal()
    log_file: str | None = None
    try:
        task_run = db.query(TaskRun).filter(TaskRun.id == UUID(task_run_id)).first()
        if not task_run:
            return

        log_file = _log_path(task_run_id)
        task_run.logs_path = log_file
        task_run.status = TaskStatus.RUNNING
        task_run.started_at = _utcnow()
        db.commit()

        handle = session_store.get(session_id)
        if handle is None:
            raise RuntimeError("No active SSH handle for this session")

        hf_token = get_setting("hf_token", db)
        mask_secrets = [hf_token] if hf_token else []

        with open(log_file, "w", encoding="utf-8") as log_f:
            log = _make_logger(log_f)
            log(f"[inferix] {step_name}\n\n")

            for command in commands:
                if not command.strip():
                    continue
                log(f"$ {_mask(command, mask_secrets)}\n")
                try:
                    out, err, rc = _exec(handle.client, command, timeout=1800, hf_token=hf_token)
                except Exception as exc:
                    out, err, rc = "", str(exc), 1

                masked_out = _mask(out, mask_secrets)
                masked_err = _mask(err, mask_secrets)
                if masked_out:
                    log(_tail(masked_out) + ("\n" if not masked_out.endswith("\n") else ""))
                if masked_err:
                    log("--- stderr ---\n" + _tail(masked_err) + ("\n" if not masked_err.endswith("\n") else ""))
                log(f"--- exit code: {rc} ---\n\n")

                if rc != 0:
                    db.refresh(task_run)
                    task_run.status = TaskStatus.FAILED
                    task_run.error_summary = (masked_err or masked_out or f"exit {rc}")[:1000]
                    db.commit()
                    return

            db.refresh(task_run)
            task_run.status = TaskStatus.SUCCESS
            log(f"[inferix] {step_name} complete\n")
            db.commit()

    except Exception as exc:
        logger.exception("Pipeline step failed: %s", step_name)
        task_run = db.query(TaskRun).filter(TaskRun.id == UUID(task_run_id)).first()
        if task_run:
            task_run.status = TaskStatus.FAILED
            task_run.error_summary = str(exc)
            db.commit()
        if log_file:
            try:
                with open(log_file, "a", encoding="utf-8") as f:
                    f.write(f"\nERROR: {exc}\n")
            except Exception:
                pass
    finally:
        task_run = db.query(TaskRun).filter(TaskRun.id == UUID(task_run_id)).first()
        if task_run:
            _finish_task_run(task_run, db)
        db.close()
